server:
  port: 8080

spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5433/app
    username: app
    password: app
    driver-class-name: org.postgresql.Driver

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
